### ISSUE TITLE
issues in start script

### ISSUE THREAD

**Issue by coderbec** [paambaati/nodequiz#3]
{"username":"abc123","security_question":"What is your mother's maiden name?","security_answer":"name","level":"info","message":"SIGNUP - FORM POST"}
internal/crypto/pbkdf2.js:56
      throw new ERR_INVALID_ARG_TYPE('digest', ['string', 'null'], digest);
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "digest" argument must be one of type string or null. Received type undefined
    at check (internal/crypto/pbkdf2.js:56:13)
    at Object.pbkdf2 (internal/crypto/pbkdf2.js:25:5)
    at AsyncWrap.<anonymous> (/Users/coder_bec/nodequiz/utils/pass.js:38:20)
    at AsyncWrap.wrap.ondone (internal/crypto/random.js:57:8) 

is produced on sign up

**Comment by venki0086** [comment]
crypto.pbkdf2Sync(password, salt, 10000, 64,'sha512').toString('base64');


ADD THIS 'sha12' in your  crypto.pdf2sync function
